# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39af224c00ee136d1342d90a3bddcde53e798034b1421a52f53c12b2bfc905a5ab72e8b3ff8a04a64c18ab3d77e30c652963841f87669486e3946508cd05d416

test:
  secret_key_base: c510228ef93e1ec326497c52af759d8b73a81ef97cb726d7f17d7690eee62b6797b420a058a05b375b5ca0e6be92ad895abf1b1342655b745669bbf7e8c96702

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
